# -*- coding: utf-8 -*-
"""Clase Funcion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdVu9HIFTXCaUtIPPJI0uBuH5RlJ6ln0
"""

import datetime
fechaActual= datetime.datetime.now()
horaActual= datetime.datetime.now()

class Funcion:
  def __init__(self, id_funcion, horario, fecha, id_sala):
    self.__id_funcion= id_funcion
    self.__horario= horario
    self.__fecha= fecha
    self.__idsala= id_sala
  def getId_Funcion(self):
    return self.__id_funcion
  def getHorario(self):
    return self.__horario
  def setFecha(self):
    return self.__fecha
  def getId_Sala(self):
    return self.__id_sala
  def mostrarFuncion(self):
    print("\nId_Funcion: "+self.getid_funcion()  +"\nId_Sala: "+self.getid_sala)
  
    def horaActual():
      horaActual= datetime.datetime.strftime(horaActual, "%H:%M:%S")
    print(horaActual)
    def fechaActual():
      fechaActual= datetime.datetime.strftime(fechaActual, "%d:%m:%Y")
    print(fechaActual)

print(fechaActual.strftime("%d/%m/%Y"))
print(horaActual.strftime("%H:%M:%S"))