# -*- coding: utf-8 -*-
"""Clases Pelicula y Butaca

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PxwHQ0m7OewzuXbhimmle63N8_wZg_YS

clase Pelicula
"""

class pelicula:
  def __init__(self,titulo,director,genero,duracion):
  self.titulo = titulo
  self.director = director
  self.genero = genero
  self.duracion = duracion
  
  def get_titulo(self):
      return self.titulo
  def get_director(self):
      return self.director
  def get_genero(self):
      return self.genero
  def get_duracion(self):
      return self.duracion
  
  def mostrarPelicula(self):
      print("\ntitulo: "+ self.gettitulo()+ "\ndirector: "+ self.getdirector()+ "\ngenero: "+ self.getgenero()+ "\nduracion: "+ str(self.getduracion()) )

titulo=input("ingrese titulo de la pelicula: ") 
director=input("ingrese el director de la pelicula: ")
genero=input("ingrese genero de la pelicula: ")
duracion=input("ingrese duracion de la pelicula: ")

pelicula=pelicula(titulo,director,genero,duracion)
print(pelicula)

"""Clase Butaca"""

class butaca:
  def __init__(self,fila,numero,sala,reservado):
    self.fila= fila
    self.numero= numero
    self.sala= sala
    self.reservado= reservado 

def get_fila(self):
  return self.fila
def get_numero(self):
  return self.numero
def get_sala(self):
  return self.sala
def get_reservado(self):
  return self.reservado

def mostrarbutaca(self):
  print("\nFila: "+str(self.getfila())+ "\nNumero: "+str(self.getnumero())+ "\nSala: "+str(self.getsala())+ "\nReservado: "+str(self.getreservado))

fila=input("ingrese numero de butaca: ")
numero=input("ingrese numero de butaca: ")
sala=input("ingrese numero de sala: ")
reservado=input("ingrese dia de reserva: ")