# -*- coding: utf-8 -*-
"""Clase Reserva

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vKrxO7rCOnAyNSgtul7_ZaWyvYS7rxx0
"""

class Reserva:
  def __init__(self, funcion, fechaDeReserva, idCliente,)
    self.__funcion= funcion
    self.__fechaDeReserva= fechaDeReserva
    self.__idCliente= idCliente
    self.__precioEntrada= 0

  def getFecha(self):
    return self.__fechaDeReserva
  def setPrecio(self,nuevoPrecio):
    self.__precioentrada= nuevoPrecio
  def validarDescuento(self):
    idCliente= self.getCliente()
    """Traer de la base de datos datos del cliente y verificar si tiene tarjeta de descuento"""
    if (tarjetaDeDescuento==True):
      descuento= Descuento(self.getFecha())
      self.setPrecio(descuento)
  def getCliente(self):
    return self.__cliente