# -*- coding: utf-8 -*-
"""Clase Descuento

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oqrei2COSXI8aTsVgjsM2rA-t7MYSZ-i
"""

class Descuento:
  def __init__(self, tipoDePelicula, tieneTarjeta, dia):
    self.__tipo= tipoDePelicula
    self.__tarjeta= tieneTarjeta
    self.__precioEntrada= 0
    self.__dia= dia
    self.__porcentajeDescuento= 0
  
  @property
  def tipo(self):
    return self.__tipoDePelicula
  @property
  def tarjeta(self):
    return self.__tieneTarjeta
  
  def dia(self):
    return self.__dia

  def valorEntrada(self):
    if (self.__tipo == "2D"):
      self.__valorEntrada= 1080
    else:
      if (self.__tipo == "3D"):
       self.__valorEntrada= 1240
    
  def porcentajeDescuento(self):
    self.valorEntrada()
    dia=self.dia()
    print(dia)
    if (dia == "0" or dia == "2" ):
      print("entre")
      self.__porcentajeDescuento = self.__valorEntrada * 0.20
      self.__valorEntrada-=self.__porcentajeDescuento
      print(f"El valor de la entrada es: {self.__valorEntrada} ")
    elif (dia == "1" or dia == "3"):
      print("entre martes")
      self.__porcentajeDescuento = self.__valorEntrada * 0.15
      self.__valorEntrada-=self.__porcentajeDescuento
      print(f"El valor de la entrada es: {self.__valorEntrada} ")
    elif (dia == "4" or dia == "5" | dia == "6"):
     self.__porcentajeDescuento = self.__valorEntrada * 0.10
     self.__valorEntrada-=self.__porcentajeDescuento
     print(f"El valor de la entrada es: {self.__valorEntrada} ")